networks:
  default: development
  sepolia:
    host: https://eth-sepolia.g.alchemy.com/v2/$WEB3_ALCHEMY_PROJECT_ID
    chainid: 11155111
    explorer: https://api-sepolia.etherscan.io/api?apiKey=$ETHERSCAN_TOKEN

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.2
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.2'
    version: 0.8.19
